Restore build?

diff --git a/makelily/makefile b/makelily/makefile
--- a/makelily/makefile
+++ b/makelily/makefile
@@ -74,18 +74,18 @@ WARN_STRING=$(WARN_COLOR)[WARNINGS]$(NO_COLOR)
 
 _tsc: _gentestsuite
 	@printf "$(TSC_STRING)\n"
-	@./node_modules/.bin/tsc || (make clean; exit 1)
+	@bash -c "./node_modules/.bin/tsc || (make clean; exit 1)"
 
 _gentestsuite: clean
 	@echo "// Generated by 'make _gentestsuite'" > ./src/tests.ts
-	@find ./src | grep -e "__tests__.*\.ts\$$" | sed 's,\./src\/\(.*\)/\(.*\)\.ts,import "\./\1/\2";,' >> ./src/tests.ts
+	@bash -c "find ./src | grep -e \"__tests__.*\.ts\$$\" | sed 's,\./src\/\(.*\)/\(.*\)\.ts,import \"\./\1/\2\";,' >> ./src/tests.ts"
 
 _stageOnly:
 	@printf "$(STAGE_STRING)\n"
 
 # Create satie.d.ts for TypeScript clients
-	@./node_modules/.bin/dts-generator --name satie --out ./dist/satie.d.ts --main 'satie/index' --baseDir ./src ./src/index.ts > /dev/null
-	@cd dist; find . | grep ".*\.d.ts" | grep -v satie.d.ts | xargs -I_FILE_ rm _FILE_
+	@bash -c "./node_modules/.bin/dts-generator --name satie --out ./dist/satie.d.ts --main 'satie/index' --baseDir ./src ./src/index.ts > /dev/null"
+	@bash -c "cd dist; find . | grep \".*\.d.ts\" | grep -v satie.d.ts | xargs -I_FILE_ rm _FILE_"
 
 _watchStage:
 	@printf "$(STAGE_STRING)\n"
@@ -101,34 +101,34 @@ _bundleOnly: _stageOnly _testOnly lint
 watch: _gentestsuite
 	@clear
 	@printf "$(WATCH_STRING)\n"
-	@CLEAN="1"; \
-	INIT="0"; \
+	@bash -c "CLEAN=\"1\"; \
+	INIT=\"0\"; \
 	./node_modules/.bin/tsc -w | \
 	while read line; do \
-	    if [[ $$line == *TS6042* ]]; then \
-		if [[ "$$CLEAN" == "1" ]]; then \
-		    printf "$(INFO_COLOR)» $$line$(NO_COLOR)\n"; \
+	    if [[ \$$line == *TS6042* ]]; then \
+		if [[ \"\$$CLEAN\" == \"1\" ]]; then \
+		    printf \"$(INFO_COLOR)» \$$line$(NO_COLOR)\n\"; \
 		    (make _watchStage) & \
-		    if [[ "$$INIT" == "0" ]]; then \
-			if [[ "x$$RUN_TESTS" != "x" ]]; then \
-			    ./node_modules/.bin/nodemon --quiet --exec "make _testOnly" -w ./dist/ -d 2 & \
+		    if [[ \"\$$INIT\" == \"0\" ]]; then \
+			if [[ \"x\$$RUN_TESTS\" != \"x\" ]]; then \
+			    ./node_modules/.bin/nodemon --quiet --exec \"make _testOnly\" -w ./dist/ -d 2 & \
 			else \
-			    printf "$(WARN_COLOR)» Tests are disabled. Run 'make watch RUN_TESTS=1' to run tests. $(NO_COLOR)\n"; \
+			    printf \"$(WARN_COLOR)» Tests are disabled. Run 'make watch RUN_TESTS=1' to run tests. $(NO_COLOR)\n\"; \
 			fi; \
-			if [[ "x$$RUN_LINT" != "x" ]]; then \
-			    ./node_modules/.bin/nodemon --quiet --exec "make lint" -w ./dist/ -d 2 &\
+			if [[ \"x\$$RUN_LINT\" != \"x\" ]]; then \
+			    ./node_modules/.bin/nodemon --quiet --exec \"make lint\" -w ./dist/ -d 2 &\
 			else \
-			    printf "$(WARN_COLOR)» Linting is disabled. Run 'make watch RUN_LINT=1' to run tests. $(NO_COLOR)\n"; \
+			    printf \"$(WARN_COLOR)» Linting is disabled. Run 'make watch RUN_LINT=1' to run tests. $(NO_COLOR)\n\"; \
 			fi; \
-			if [[ "x$$RUN_SATIEAPP" != "x" ]]; then \
+			if [[ \"x\$$RUN_SATIEAPP\" != \"x\" ]]; then \
 			    sleep 5; \
 			    cd ./webapp; \
 			    make watch RUN_DEVSRV=1 & \
 			    cd ..; \
 			else \
-			    printf "$(WARN_COLOR)» The Satie app is disabled. Run 'make watch RUN_SATIEAPP=1' to run the test server. $(NO_COLOR)\n"; \
+			    printf \"$(WARN_COLOR)» The Satie app is disabled. Run 'make watch RUN_SATIEAPP=1' to run the test server. $(NO_COLOR)\n\"; \
 			fi; \
-			if [[ "x$$RUN_DEVSRV" != "x" ]]; then \
+			if [[ \"x\$$RUN_DEVSRV\" != \"x\" ]]; then \
 			    ./node_modules/.bin/webpack-dev-server \
 				--debug \
 				--devtool source-map \
@@ -141,22 +141,22 @@ watch: _gentestsuite
 				--host 0.0.0.0 \
 				--port 8009 & \
 			else \
-			    printf "$(WARN_COLOR)» The dev server is disabled. Run 'make watch RUN_DEVSRV=1' to enable. $(NO_COLOR)\n"; \
+			    printf \"$(WARN_COLOR)» The dev server is disabled. Run 'make watch RUN_DEVSRV=1' to enable. $(NO_COLOR)\n\"; \
 			fi; \
-			INIT="1"; \
+			INIT=\"1\"; \
 		    fi; \
 		else \
-		    printf "$(ERROR_COLOR)» $$line$(NO_COLOR)\n"; \
+		    printf \"$(ERROR_COLOR)» \$$line$(NO_COLOR)\n\"; \
 		fi; \
-	    elif [[ $$line == *TS6032* ]]; then \
+	    elif [[ \$$line == *TS6032* ]]; then \
 		clear; \
-		CLEAN="1"; \
-		printf "$(INFO_COLOR)» $$line$(NO_COLOR)\n"; \
+		CLEAN=\"1\"; \
+		printf \"$(INFO_COLOR)» \$$line$(NO_COLOR)\n\"; \
 	    else \
-		CLEAN="0"; \
-		printf "$(ERROR_COLOR)» $$line$(NO_COLOR)\n"; \
+		CLEAN=\"0\"; \
+		printf \"$(ERROR_COLOR)» \$$line$(NO_COLOR)\n\"; \
 	    fi; \
-	done;
+	done;"
 
 tsd: ./node_modules/tsd/build/cli.js
 	./node_modules/tsd/build/cli.js link -so
@@ -164,19 +164,19 @@ tsd: ./node_modules/tsd/build/cli.js
 
 smufl:
 	@bash -c "echo -ne \"$$BRAVURA_HEADER\"" > ./src/models/smufl/bravura.ts
-	@cat ./vendor/bravura/bravura_metadata.json | jq '{fontName: .fontName, fontVersion: .fontVersion, engravingDefaults: .engravingDefaults, glyphBBoxes: [(.glyphBBoxes | to_entries[] | .value.bBoxNE + .value.bBoxSW + [.key])], glyphsWithAnchors: .glyphsWithAnchors, ligatures: .ligatures}' >> ./src/models/smufl/bravura.ts
-	@echo "; export default Bravura;" >> ./src/models/smufl/bravura.ts
+	@bash -c "cat ./vendor/bravura/bravura_metadata.json | jq '{fontName: .fontName, fontVersion: .fontVersion, engravingDefaults: .engravingDefaults, glyphBBoxes: [(.glyphBBoxes | to_entries[] | .value.bBoxNE + .value.bBoxSW + [.key])], glyphsWithAnchors: .glyphsWithAnchors, ligatures: .ligatures}' >> ./src/models/smufl/bravura.ts"
+	@bash -c "echo '; export default Bravura;' >> ./src/models/smufl/bravura.ts"
 	
-	@bash -c "echo -ne \"$$GLYPHNAMES_HEADER\"" > ./src/models/smufl/glyphnames.ts
+	@bash -c "echo -ne \"$$GLYPHNAMES_HEADER\" > ./src/models/smufl/glyphnames.ts"
 	@cat ./vendor/smufl/glyphnames.json | jq '[to_entries[] | {key: .key, value: .value.codepoint}] | from_entries' >> ./src/models/smufl/glyphnames.ts
-	@echo "; export default names;" >> ./src/models/smufl/glyphnames.ts
+	@bash -c "echo '; export default names;' >> ./src/models/smufl/glyphnames.ts"
 	@printf "$(INFO_COLOR)» SMuFL built successfully.$(NO_COLOR)\n"; \
 
 TS_FILES = $(shell find src/ -type f -name '*.ts')
 
 lint: node_modules/.bin/tslint
 	@printf "$(LINT_STRING)\n"
-	@set -o pipefail; ./node_modules/.bin/tslint $(TS_FILES) | sed -e "s/\(.*\)/[tslint] \x1b[31;01m\1\x1b[0m/"
+	@bash -c "set -o pipefail; ./node_modules/.bin/tslint $(TS_FILES) | sed -e \"s/\(.*\)/[tslint] \x1b[31;01m\1\x1b[0m/\""
 
 vendor/tslint/bin/tslint.js:
 	@git submodule update --init --recursive
@@ -187,13 +187,13 @@ test: build _testOnly lint
 
 _testOnly:
 	@printf "$(TEST_STRING)\n"
-	@if [ "x$$TEST" == "x" ]; then find ./dist -type f | grep "__tests__.*js\$$" | xargs ./node_modules/mocha/bin/mocha -t 3000; else find ./dist -type f | grep "__tests__.*js\$$" | xargs ./node_modules/mocha/bin/mocha -t 3000 --grep "$$TEST" 2>&1; fi
+	@bash -c "if [ \"x\$$TEST\" == \"x\" ]; then find ./dist -type f | grep \"__tests__.*js\\$$\" | xargs ./node_modules/mocha/bin/mocha -t 3000; else find ./dist -type f | grep \"__tests__.*js\\$$\" | xargs ./node_modules/mocha/bin/mocha -t 3000 --grep \"\$$TEST\" 2>&1; fi"
 
 test_all: test lint
 
 coverage: build
 	@printf "$(COVERAGE_STRING)\n"
-	@find ./dist -type f | grep "__tests__.*js\$$" | xargs istanbul cover node_modules/mocha/bin/_mocha -- -R list
+	@bash -c "find ./dist -type f | grep "__tests__.*js\$$" | xargs istanbul cover node_modules/mocha/bin/_mocha -- -R list"
 
 ./webapp/node_modules:
 	cd ./webapp; npm install
diff --git a/makelily/webapp/makefile b/makelily/webapp/makefile
--- a/makelily/webapp/makefile
+++ b/makelily/webapp/makefile
@@ -23,23 +23,23 @@ TS_FILES = $(shell find src/ -type f -name '*.ts')
 watch:
 	@clear
 	@printf "$(WATCH_STRING)\n"
-	@CLEAN="1"; \
-	INIT="0"; \
+	@bash -c "CLEAN=\"1\"; \
+	INIT=\"0\"; \
 	../node_modules/.bin/tsc -w | \
 	while read line; do \
-	    if [[ $$line == *TS6042* ]]; then \
-		if [[ "$$CLEAN" == "1" ]]; then \
-		    printf "satieapp$(INFO_COLOR)» $$line$(NO_COLOR)\n"; \
+	    if [[ \$$line == *TS6042* ]]; then \
+		if [[ \"\$$CLEAN\" == \"1\" ]]; then \
+		    printf \"satieapp$(INFO_COLOR)» \$$line$(NO_COLOR)\n\"; \
 		    cd ./src; \
-		    find -type f -name "*.css" -exec install -m 644 -D "{}" ../dist/{} ";" ; \
+		    find -type f -name \"*.css\" -exec install -m 644 -D \"{}\" ../dist/{} \";\" ; \
 		    cd ..; \
-		    if [[ "$$INIT" == "0" ]]; then \
-			if [[ "x$$RUN_LINT" != "x" ]]; then \
-			    ../node_modules/.bin/nodemon --quiet --exec "make lint" -w ./dist/ -d 2 &\
+		    if [[ \"\$$INIT\" == \"0\" ]]; then \
+			if [[ \"x\$$RUN_LINT\" != \"x\" ]]; then \
+			    ../node_modules/.bin/nodemon --quiet --exec \"make lint\" -w ./dist/ -d 2 &\
 			else \
-			    printf "satieapp$(WARN_COLOR)» Linting is disabled. Run 'make watch RUN_LINT=1' to run tests. $(NO_COLOR)\n"; \
+			    printf \"satieapp$(WARN_COLOR)» Linting is disabled. Run 'make watch RUN_LINT=1' to run tests. $(NO_COLOR)\n\"; \
 			fi; \
-			if [[ "x$$RUN_DEVSRV" != "x" ]]; then \
+			if [[ \"x\$$RUN_DEVSRV\" != \"x\" ]]; then \
 			    ../node_modules/.bin/webpack-dev-server \
 				--debug \
 				--devtool source-map \
@@ -53,40 +53,43 @@ watch:
 				--host 0.0.0.0 \
 				--port 4200 & \
 			else \
-			    printf "satieapp$(WARN_COLOR)» The dev server is disabled. Run 'make watch RUN_DEVSRV=1' to enable. $(NO_COLOR)\n"; \
+			    printf \"satieapp$(WARN_COLOR)» The dev server is disabled. Run 'make watch RUN_DEVSRV=1' to enable. $(NO_COLOR)\n\"; \
 			fi; \
-			INIT="1"; \
+			INIT=\"1\"; \
 		    fi; \
 		else \
-		    printf "satieapp$(ERROR_COLOR)» $$line$(NO_COLOR)\n"; \
+		    printf \"satieapp$(ERROR_COLOR)» \$$line$(NO_COLOR)\n\"; \
 		fi; \
-	    elif [[ $$line == *TS6032* ]]; then \
+	    elif [[ \$$line == *TS6032* ]]; then \
 		clear; \
-		CLEAN="1"; \
-		printf "satieapp$(INFO_COLOR)» $$line$(NO_COLOR)\n"; \
+		CLEAN=\"1\"; \
+		printf \"satieapp$(INFO_COLOR)» \$$line$(NO_COLOR)\n\"; \
 	    else \
-		CLEAN="0"; \
-		printf "satieapp$(ERROR_COLOR)» $$line$(NO_COLOR)\n"; \
+		CLEAN=\"0\"; \
+		printf \"satieapp$(ERROR_COLOR)» \$$line$(NO_COLOR)\n\"; \
 	    fi; \
-	done;
+	done;"
 
 lint:
 	@printf "$(LINT_STRING)\n"
-	@set -o pipefail; ../node_modules/.bin/tslint $(TS_FILES) | sed -e "s/\(.*\)/[tslint] \x1b[31;01m\1\x1b[0m/"
+	@bash -c "set -o pipefail; ../node_modules/.bin/tslint $(TS_FILES) | sed -e \"s/\(.*\)/[tslint] \x1b[31;01m\1\x1b[0m/\""
 
 build: clean lint
-	./node_modules/.bin/webpack -p
-	cp -RLf ./static/* ./dist/satie/
-	cd ./dist/satie; \
+	bash -c "../node_modules/.bin/tsc"
+	bash -c "cd ./src; \
+	    find -type f -name \"*.css\" -exec install -m 644 -D \"{}\" ../dist/{} \";\" ;"
+	bash -c "../node_modules/.bin/webpack -p"
+	bash -c "cp -RLf ./static/* ./dist/satie/"
+	bash -c "cp ../dist/satie-bundled-min.js ./dist/satie/satie.js"
+	bash -c "mv ./dist/satie/index-prod.html ./dist/satie/index.html"
+	bash -c "cd ./dist/satie; \
 	touch ./.nojekyll; \
-	sed -i.bak 's,"/,"https://nettek.ca/satie/,g' ./index.html; \
-	rm *.bak; \
 	mkdir tests; \
 	ln -s ../index.html tests/; \
 	mkdir _term; \
 	ln -s ../index.html _term/; \
 	cd tests; \
-	node --harmony -e 'Array.prototype.forEach.call("0123456789", a => Array.prototype.forEach.call("0123456789 ", b => Array.prototype.forEach.call(b === " " ? " " : " qwertyuiopasdfghjklzxcvbnm", c => console.log("ln -s ../_term " + a + b + c + ";"))))' | bash --
+	node --harmony -e 'Array.prototype.forEach.call(\"0123456789\", a => Array.prototype.forEach.call(\"0123456789 \", b => Array.prototype.forEach.call(b === \" \" ? \" \" : \" qwertyuiopasdfghjklzxcvbnm\", c => console.log(\"ln -s ../_term \" + a + b + c + \";\"))))' | bash --"
 
 deploy:
 	cd ../; make build
